/*
 * This file is part of Hackli GUI Studio (https://github.com/hankli22/hackli-gui-studio).
 * Copyright (C) 2026 hankli22 and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.hackli.guidesigner.export;

import com.hackli.guidesigner.model.AnchorX;
import com.hackli.guidesigner.model.AnchorY;
import com.hackli.guidesigner.model.DocumentStore;
import com.hackli.guidesigner.model.ContainerStyle;
import com.hackli.guidesigner.model.InputFilter;
import com.hackli.guidesigner.model.LayoutMode;
import com.hackli.guidesigner.model.Orientation;
import com.hackli.guidesigner.model.TextAlign;
import com.hackli.guidesigner.model.UiDocument;
import com.hackli.guidesigner.model.UiNode;
import com.hackli.guidesigner.model.UiType;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates a complete plugin GUI class that extends the Hackli GUI Studio
 * runtime {@code UiScreen}, including a backend handler class with stubs for
 * every interactive widget.
 */
public class JavaExporter {
    private JavaExporter() {}

    public static String generate(UiDocument doc, String pkg) {
        String className = DocumentStore.toJava(doc.name);
        StringBuilder sb = new StringBuilder();

        header(sb);

        sb.append("package ").append(pkg).append(";\n\n");

        sb.append("import com.hackli.guidesigner.model.AnchorX;\n");
        sb.append("import com.hackli.guidesigner.model.AnchorY;\n");
        sb.append("import com.hackli.guidesigner.model.InputFilter;\n");
        sb.append("import com.hackli.guidesigner.model.LayoutMode;\n");
        sb.append("import com.hackli.guidesigner.model.TextAlign;\n");
        sb.append("import com.hackli.guidesigner.model.UiDocument;\n");
        sb.append("import com.hackli.guidesigner.model.UiNode;\n");
        sb.append("import com.hackli.guidesigner.model.ContainerStyle;\n");
        sb.append("import com.hackli.guidesigner.model.Orientation;\n");
        sb.append("import com.hackli.guidesigner.runtime.UiCallbacks;\n");
        sb.append("import com.hackli.guidesigner.runtime.UiScreen;\n\n");

        sb.append("/**\n");
        sb.append(" * GUI \"").append(esc(doc.name)).append("\" generated by Hackli GUI Studio.\n");
        sb.append(" * Open it from a module or command, e.g.:\n");
        sb.append(" * {@code MinecraftClient.getInstance().setScreen(new ").append(className).append("());}\n");
        sb.append(" * The layout can be rearranged in-game: enable the \"GUI Layout Editor\" module.\n");
        sb.append(" */\n");
        sb.append("public class ").append(className).append(" extends UiScreen {\n\n");
        sb.append("    public ").append(className).append("() {\n");
        sb.append("        super(\"").append(esc(doc.name)).append("\", buildDocument(), new ").append(className).append("Handler());\n");
        sb.append("    }\n\n");

        // ---- document builder ----
        sb.append("    private static UiDocument buildDocument() {\n");
        sb.append("        UiDocument doc = new UiDocument(\"").append(esc(doc.name)).append("\");\n");
        sb.append("        doc.root = ").append(nodeExpr(doc.root, "            ")).append(";\n");
        sb.append("        return doc;\n");
        sb.append("    }\n\n");

        // ---- handler ----
        sb.append("    public static class ").append(className).append("Handler implements UiCallbacks {\n\n");
        sb.append("        @Override\n");
        sb.append("        public void onAction(String id, String event, String value) {\n");
        sb.append("            switch (id) {\n");

        Map<String, UiNode> byId = new LinkedHashMap<>();
        for (UiNode node : doc.interactiveNodes()) {
            if (!node.id.isEmpty() && !byId.containsKey(node.id)) byId.put(node.id, node);
        }

        for (Map.Entry<String, UiNode> entry : byId.entrySet()) {
            UiNode node = entry.getValue();
            String method = handlerMethod(node);

            sb.append("                case \"").append(esc(node.id)).append("\" -> {\n");

            switch (node.type) {
                case BUTTON -> sb.append("                    if (event.equals(\"click\")) ").append(method).append("();\n");
                case TEXTBOX -> sb.append("                    if (event.equals(\"change\")) ").append(method).append("(value);\n");
                case CHECKBOX -> sb.append("                    if (event.equals(\"toggle\")) ").append(method).append("(Boolean.parseBoolean(value));\n");
                case SLIDER -> sb.append("                    if (event.equals(\"release\")) ").append(method).append("(Double.parseDouble(value));\n");
                case DROPDOWN -> sb.append("                    if (event.equals(\"select\")) ").append(method).append("(value);\n");
                default -> {}
            }

            sb.append("                }\n");
        }

        sb.append("                default -> {}\n");
        sb.append("            }\n");
        sb.append("        }\n\n");

        for (Map.Entry<String, UiNode> entry : byId.entrySet()) {
            UiNode node = entry.getValue();

            sb.append("        /** Backend stub for \"").append(esc(node.id)).append("\". Fill me in! */\n");
            switch (node.type) {
                case BUTTON -> sb.append("        public void ").append(handlerMethod(node)).append("() {\n            // TODO: handle \"").append(esc(node.id)).append("\" click\n        }\n\n");
                case TEXTBOX -> sb.append("        public void ").append(handlerMethod(node)).append("(String value) {\n            // TODO: handle \"").append(esc(node.id)).append("\" text change\n        }\n\n");
                case CHECKBOX -> sb.append("        public void ").append(handlerMethod(node)).append("(boolean value) {\n            // TODO: handle \"").append(esc(node.id)).append("\" toggle\n        }\n\n");
                case SLIDER -> sb.append("        public void ").append(handlerMethod(node)).append("(double value) {\n            // TODO: handle \"").append(esc(node.id)).append("\" slide\n        }\n\n");
                case DROPDOWN -> sb.append("        public void ").append(handlerMethod(node)).append("(String value) {\n            // TODO: handle \"").append(esc(node.id)).append("\" selection\n        }\n\n");
                default -> {}
            }
        }

        sb.append("    }\n");
        sb.append("}\n");

        return sb.toString();
    }

    // ================= node expression =================

    private static String nodeExpr(UiNode node, String indent) {
        StringBuilder sb = new StringBuilder(indent);
        sb.append(nodeFactory(node));

        List<String> calls = new ArrayList<>();

        if (!node.text.isEmpty() && node.type.hasText()) calls.add(".text(" + q(node.text) + ")");
        if (node.type == UiType.TEXTBOX && !node.placeholder.isEmpty()) calls.add(".placeholder(" + q(node.placeholder) + ")");
        if (node.type == UiType.CHECKBOX && node.checked) calls.add(".checked(true)");
        if (node.type == UiType.NUMBER) {
            calls.add(".sliderValue(" + num(node.value) + ").range(" + num(node.min) + ", " + num(node.max) + ")");
            if (!node.integer) calls.add(".integer(false)");
            if (!node.showSlider) calls.add(".showSlider(false)");
            if (!node.showButtons) calls.add(".showButtons(false)");
            if (node.step != 1) calls.add(".step(" + num(node.step) + ")");
        }
        if (node.type == UiType.TEXTURE) {
            if (!node.texture.isEmpty()) calls.add(".textureRef(" + q(node.texture) + ")");
            if (node.rotation != 0) calls.add(".rotation(" + num(node.rotation) + ")");
        }
        if (node.type == UiType.KEYBIND) {
            calls.add(".keybind(" + node.key + ", " + node.modifiers + ", " + node.keyIsKey + ")");
        }
        if (node.type == UiType.ITEM) {
            calls.add(".item(" + q(node.itemId) + ", " + node.itemCount + ")");
        }
        if (node.type == UiType.ENTITY) {
            calls.add(".entityId(" + q(node.entityId) + ")");
        }
        if (node.type == UiType.SELECT && node.itemCountSelected >= 0) {
            calls.add(".selectedCount(" + node.itemCountSelected + ")");
        }
        if (node.type == UiType.SLIDER && (node.min != 0 || node.max != 0 || node.value != 0)) {
            calls.add(".sliderValue(" + num(node.value) + ").range(" + num(node.min) + ", " + num(node.max) + ")");
        }
        if (node.type == UiType.DROPDOWN && !node.options.isEmpty()) {
            calls.add(".options(" + qList(node.options) + ")"
                + (node.selected != null ? ".selected(" + q(node.selected) + ")" : ""));
        }
        if (!node.type.isContainer && (node.width > 0 || node.height > 0)) {
            calls.add(".size(" + num(node.width) + ", " + num(node.height) + ")");
        }
        if (!node.textColor.isEmpty()) calls.add(".textColor(" + q(node.textColor) + ")");
        if (node.type.hasText() && node.textAlign != TextAlign.LEFT) {
            calls.add(".textAlign(TextAlign." + node.textAlign.name() + ")");
        }
        if (node.type == UiType.TEXTBOX && node.maxLength > 0) calls.add(".maxLength(" + node.maxLength + ")");
        if (node.type == UiType.TEXTBOX && node.inputFilter != InputFilter.NONE) {
            calls.add(".inputFilter(InputFilter." + node.inputFilter.name() + ")");
        }
        if (!node.handler.isEmpty()) calls.add(".handler(" + q(node.handler) + ")");
        // Hover text applies to every widget kind, so it is not type gated.
        if (node.tooltip != null && !node.tooltip.isEmpty()) calls.add(".tooltip(" + q(node.tooltip) + ")");
        if (node.layout != LayoutMode.FLOW) calls.add(".layout(LayoutMode." + node.layout.name() + ")");
        if (node.anchorX != AnchorX.LEFT || node.anchorY != AnchorY.TOP) {
            calls.add(".anchor(AnchorX." + node.anchorX.name() + ", AnchorY." + node.anchorY.name() + ")");
        }
        if (node.x != 0 || node.y != 0) calls.add(".pos(" + num(node.x) + ", " + num(node.y) + ")");
        if (node.type.isContainer && node.style != ContainerStyle.PANEL) {
            calls.add(".style(ContainerStyle." + node.style.name() + ")");
        }
        if (node.collapsed) calls.add(".collapsed(true)");
        if (node.type.isContainer && node.orientation != Orientation.VERTICAL) {
            calls.add(".orientation(Orientation." + node.orientation.name() + ")");
        }
        if (!node.visible) calls.add(".visible(false)");

        String childIndent = indent + "    ";
        for (String call : calls) sb.append("\n").append(childIndent).append(call);

        for (UiNode child : node.children) {
            sb.append("\n").append(childIndent).append(".child(\n");
            sb.append(nodeExpr(child, childIndent + "    "));
            sb.append("\n").append(childIndent).append(")");
        }

        return sb.toString();
    }

    private static String nodeFactory(UiNode node) {
        return switch (node.type) {
            case CONTAINER -> "UiNode.container(\"" + esc(node.id) + "\", " + num(node.width) + ", " + num(node.height) + ")";
            case LABEL -> "UiNode.label(\"" + esc(node.id) + "\")";
            case BUTTON -> "UiNode.button(\"" + esc(node.id) + "\")";
            case TEXTBOX -> "UiNode.textBox(\"" + esc(node.id) + "\")";
            case CHECKBOX -> "UiNode.checkBox(\"" + esc(node.id) + "\")";
            case SLIDER -> "UiNode.slider(\"" + esc(node.id) + "\")";
            case DROPDOWN -> "UiNode.dropdown(\"" + esc(node.id) + "\")";
            case SEPARATOR -> "UiNode.separator(\"" + esc(node.id) + "\")";
            case NUMBER -> "UiNode.number(\"" + esc(node.id) + "\")";
            case TEXTURE -> "UiNode.texture(\"" + esc(node.id) + "\")";
            case KEYBIND -> "UiNode.keybind(\"" + esc(node.id) + "\")";
            case ITEM -> "UiNode.item(\"" + esc(node.id) + "\")";
            case ENTITY -> "UiNode.entity(\"" + esc(node.id) + "\")";
            case SELECT -> "UiNode.select(\"" + esc(node.id) + "\")";
        };
    }

    // ================= helpers =================

    private static String handlerMethod(UiNode node) {
        String name = node.handler == null || node.handler.isEmpty() ? node.id : node.handler;
        return "on" + DocumentStore.toJava(name);
    }

    private static void header(StringBuilder sb) {
        sb.append("/*\n");
        sb.append(" * Generated by Hackli GUI Studio (GPLv3).\n");
        sb.append(" *\n");
        sb.append(" * This file is part of your Meteor Client plugin. Plugin code developed with\n");
        sb.append(" * Hackli GUI Studio must be released under the GNU General Public License v3:\n");
        sb.append(" *     https://www.gnu.org/licenses/gpl-3.0.txt\n");
        sb.append(" *\n");
        sb.append(" * Requires the Hackli GUI Studio mod to be installed at runtime (for layout\n");
        sb.append(" * rendering and in-game layout editing).\n");
        sb.append(" */\n\n");
    }

    private static String q(String value) {
        return "\"" + esc(value) + "\"";
    }

    private static String qList(List<String> values) {
        StringBuilder sb = new StringBuilder();
        sb.append('"');
        for (int i = 0; i < values.size(); i++) {
            if (i > 0) sb.append("\", \"");
            sb.append(esc(values.get(i)));
        }
        sb.append('"');
        return sb.toString();
    }

    private static String esc(String value) {
        if (value == null) return "";
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String num(double value) {
        if (value == Math.floor(value) && !Double.isInfinite(value)) {
            return String.valueOf((long) value);
        }
        return String.valueOf(value);
    }
}
