/*
 * This file is part of Hackli GUI Studio (https://github.com/hankli22/hackli-gui-studio).
 * Copyright (C) 2026 hankli22 and contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.hackli.guidesigner.export;

import com.hackli.guidesigner.model.DocumentStore;
import com.hackli.guidesigner.model.LayoutMode;
import com.hackli.guidesigner.model.UiDocument;
import com.hackli.guidesigner.model.UiNode;
import com.hackli.guidesigner.model.UiType;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates a self-contained Meteor {@code WidgetScreen} using plain Meteor
 * widgets. No runtime dependency on Hackli GUI Studio, but widget positions
 * designed with absolute layout are converted to flow layout (the generated
 * source contains a warning about it).
 */
public class MeteorExporter {
    private MeteorExporter() {}

    public static String generate(UiDocument doc, String pkg) {
        String className = DocumentStore.toJava(doc.name) + "Static";
        StringBuilder sb = new StringBuilder();

        header(sb);

        sb.append("package ").append(pkg).append(";\n\n");

        sb.append("import meteordevelopment.meteorclient.gui.GuiThemes;\n");
        sb.append("import meteordevelopment.meteorclient.gui.WidgetScreen;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.WLabel;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.WKeybind;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.containers.WTable;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.containers.WSection;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.containers.WWindow;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.containers.WView;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.containers.WVerticalList;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.containers.WHorizontalList;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.input.WTextBox;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.input.WSlider;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.input.WDropdown;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.input.WIntEdit;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.input.WDoubleEdit;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.pressable.WButton;\n");
        sb.append("import meteordevelopment.meteorclient.gui.widgets.pressable.WCheckbox;\n");
        sb.append("import meteordevelopment.meteorclient.utils.render.color.Color;\n");
        sb.append("import meteordevelopment.meteorclient.utils.misc.Keybind;\n\n");

        sb.append("/**\n");
        sb.append(" * GUI \"").append(esc(doc.name)).append("\" generated by Hackli GUI Studio (static export).\n");
        sb.append(" * Open it from a module or command: {@code MinecraftClient.getInstance().setScreen(new ").append(className).append("());}\n");
        sb.append(" */\n");
        sb.append("public class ").append(className).append(" extends WidgetScreen {\n\n");
        sb.append("    public ").append(className).append("() {\n");
        sb.append("        super(GuiThemes.get(), \"").append(esc(doc.name)).append("\");\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public void initWidgets() {\n");

        // Root becomes a WSection
        sb.append("        // Root container\n");
        sb.append("        WSection root = theme.section(\"").append(esc(rootTitle(doc.root))).append("\");\n");
        sb.append("        add(root).top().expandX();\n");

        emitChildren(sb, doc.root, "root", "        ");

        sb.append("    }\n");

        emitHandlerStubs(sb, doc);

        sb.append("}\n");

        return sb.toString();
    }

    // ================= children emission =================

    private static void emitChildren(StringBuilder sb, UiNode parent, String parentVar, String indent) {
        // Inside a WTable the cells are added in order and a row break is emitted
        // whenever the column count is reached, mirroring Meteor's table.row().
        boolean table = parent.style == com.hackli.guidesigner.model.ContainerStyle.TABLE;
        int columns = table ? com.hackli.guidesigner.render.MeteorLayout.tableColumns(parent) : 0;
        int column = 0;

        for (UiNode child : parent.children) {
            if (!child.visible) continue;

            if (table) {
                UiNode.Cell cell = child.cell;
                // An explicit hint on this cell starts a new row (Meteor's row()).
                if (column > 0 && cell != null && (cell.row || cell.column)) {
                    sb.append(indent).append(parentVar).append(".row();\n");
                    column = 0;
                }
            }

            emitChild(sb, parent, child, parentVar, indent);

            if (table) {
                column++;
                if (column >= columns) {
                    sb.append(indent).append(parentVar).append(".row();\n");
                    column = 0;
                }
            }
        }
    }

    private static void emitChild(StringBuilder sb, UiNode parent, UiNode child,
                                  String parentVar, String indent) {
        {
            if (child.type == UiType.CONTAINER) {
                if (child.layout == LayoutMode.ABSOLUTE) {
                    sb.append(indent).append("// Absolute layout is not representable in a static export; children are flowed.\n");
                }

                String var = var(child.id);
                String title = esc(child.text.isEmpty() ? child.id : child.text);
                sb.append(indent).append("// Container \"").append(esc(child.id)).append("\"\n");
                switch (child.style) {
                    case SECTION -> {
                        sb.append(indent).append("WSection ").append(var)
                            .append(" = theme.section(\"").append(title).append("\", ")
                            .append(!child.collapsed).append(");\n");
                    }
                    case VIEW -> {
                        sb.append(indent).append("WView ").append(var).append(" = theme.view();\n");
                        sb.append(indent).append(var).append(".maxHeight = ")
                            .append(child.height > 0 ? String.valueOf((long) child.height) : "400").append(";\n");
                    }
                    case TABLE -> {
                        // WTable has no title and no padding of its own.
                        sb.append(indent).append("WTable ").append(var).append(" = theme.table();\n");
                    }
                    default -> {
                        sb.append(indent).append("WWindow ").append(var).append(" = theme.window(\"")
                            .append(title).append("\");\n");
                        sb.append(indent).append(var).append(".id = \"").append(esc(child.id)).append("\";\n");
                    }
                }
                sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");

                emitChildren(sb, child, var, indent + "    ");
                return;
            }

            String var = var(child.id);

            switch (child.type) {
                case LABEL -> {
                    if (!child.textColor.isEmpty()) {
                        sb.append(indent).append("WLabel ").append(var).append(" = theme.label(\"").append(esc(child.text.isEmpty() ? child.id : child.text)).append("\");\n");
                        sb.append(indent).append(var).append(".color(").append(colorExpr(child.textColor)).append(");\n");
                        sb.append(indent).append(parentVar).append(".add(").append(var).append(");\n");
                    } else {
                        sb.append(indent).append(parentVar).append(".add(theme.label(\"").append(esc(child.text.isEmpty() ? child.id : child.text)).append("\"));\n");
                    }
                }
                case BUTTON -> {
                    sb.append(indent).append("WButton ").append(var).append(" = theme.button(\"").append(esc(child.text.isEmpty() ? child.id : child.text)).append("\");\n");
                    tooltip(sb, indent, var, child);
                    sb.append(indent).append(var).append(".action = () -> ").append(method(child)).append("();\n");
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");
                    if (child.textAlign != com.hackli.guidesigner.model.TextAlign.LEFT) {
                        sb.append(indent).append("// textAlign \"").append(child.textAlign.name()).append("\" is not representable for buttons in a static export.\n");
                    }
                }
                case TEXTBOX -> {
                    String filter = textBoxFilterExpr(child);
                    if (filter == null) {
                        sb.append(indent).append("WTextBox ").append(var).append(" = theme.textBox(\"").append(esc(child.text)).append("\", \"").append(esc(child.placeholder)).append("\");\n");
                    } else {
                        sb.append(indent).append("WTextBox ").append(var).append(" = theme.textBox(\"").append(esc(child.text)).append("\", \"").append(esc(child.placeholder)).append("\", ").append(filter).append(");\n");
                    }
                    sb.append(indent).append(var).append(".action = () -> ").append(method(child)).append("(").append(var).append(".get());\n");
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");
                }
                case CHECKBOX -> {
                    sb.append(indent).append("WCheckbox ").append(var).append(" = theme.checkbox(").append(child.checked).append(");\n");
                    sb.append(indent).append(var).append(".action = () -> ").append(method(child)).append("(").append(var).append(".checked);\n");
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(");\n");
                }
                case SLIDER -> {
                    double min = child.min;
                    double max = child.max;
                    sb.append(indent).append("WSlider ").append(var).append(" = theme.slider(").append(num(child.value)).append(", ").append(num(min)).append(", ").append(num(max)).append(");\n");
                    sb.append(indent).append(var).append(".actionOnRelease = () -> ").append(method(child)).append("(").append(var).append(".get());\n");
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");
                }
                case DROPDOWN -> {
                    sb.append(indent).append("WDropdown<String> ").append(var).append(" = theme.dropdown(").append(qList(child.options)).append(", ")
                        .append(q(child.selected != null ? child.selected : (child.options.isEmpty() ? "-" : child.options.getFirst()))).append(");\n");
                    sb.append(indent).append(var).append(".action = () -> ").append(method(child)).append("(").append(var).append(".get());\n");
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(");\n");
                }
                case NUMBER -> {
                    // Meteor's WIntEdit / WDoubleEdit: value, min, max, sliderMin, sliderMax(, noSlider)
                    if (child.integer) {
                        sb.append(indent).append("WIntEdit ").append(var).append(" = theme.intEdit(")
                            .append(Math.round(child.value)).append(", ").append(Math.round(child.min))
                            .append(", ").append(Math.round(child.max)).append(", ")
                            .append(Math.round(child.min)).append(", ").append(Math.round(child.max))
                            .append(", ").append(!child.showSlider).append(");\n");
                    } else {
                        sb.append(indent).append("WDoubleEdit ").append(var).append(" = theme.doubleEdit(")
                            .append(child.value).append(", ").append(child.min).append(", ").append(child.max)
                            .append(", ").append(child.min).append(", ").append(child.max).append(");\n");
                    }
                    sb.append(indent).append(var).append(".action = () -> ").append(method(child))
                        .append("(").append(var).append(".get());\n");
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");
                }
                case SEPARATOR -> {
                    if (child.text.isEmpty()) {
                        sb.append(indent).append(parentVar).append(".add(theme.horizontalSeparator());\n");
                    } else {
                        sb.append(indent).append(parentVar).append(".add(theme.horizontalSeparator(\"").append(esc(child.text)).append("\"));\n");
                    }
                }
                case KEYBIND -> {
                    // Meteor's WKeybind: theme.keybind(Keybind.fromKeys(code, mods))
                    // or fromButton(code) for a mouse binding.
                    sb.append(indent).append("Keybind ").append(var).append("Bind = Keybind.")
                        .append(child.keyIsKey ? "fromKeys(" : "fromButton(")
                        .append(child.key);
                    if (child.keyIsKey) sb.append(", ").append(child.modifiers);
                    sb.append(");\n");
                    sb.append(indent).append("WKeybind ").append(var).append(" = theme.keybind(")
                        .append(var).append("Bind);\n");
                    tooltip(sb, indent, var, child);
                    sb.append(indent).append(var).append(".action = () -> ").append(method(child))
                        .append("();\n");
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");
                    sb.append(indent).append("// the binding lives in ").append(var)
                        .append("Bind; wire it into your module's KeybindSetting.\n");
                }
                case ITEM -> {
                    // WItem takes an ItemStack: theme.item(new ItemStack(Items.DIAMOND, 1)).
                    String item = itemExpr(child.itemId);
                    sb.append(indent).append("WItem ").append(var).append(" = theme.item(new ItemStack(")
                        .append(item).append(", ").append(Math.max(1, Math.min(64, child.itemCount)))
                        .append("));\n");
                    tooltip(sb, indent, var, child);
                    sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");
                }
                case ENTITY -> {
                    // Meteor shows an entity as its spawn egg item.
                    String egg = spawnEggExpr(child.entityId);
                    if (egg == null) {
                        sb.append(indent).append("// entity \"").append(esc(child.entityId))
                            .append("\" has no spawn egg; a label stands in for it.\n");
                        sb.append(indent).append(parentVar).append(".add(theme.label(\"")
                            .append(esc(child.entityId)).append("\"));\n");
                    } else {
                        sb.append(indent).append("WItem ").append(var).append(" = theme.item(new ItemStack(")
                            .append(egg).append("));\n");
                        tooltip(sb, indent, var, child);
                        sb.append(indent).append(parentVar).append(".add(").append(var).append(")").append(expand(parent, child)).append(";\n");
                    }
                }
                case SELECT -> {
                    // GuiTheme.selectW: a "Select" button and the count beside it.
                    String label = com.hackli.guidesigner.render.MeteorPainter.selectLabel(child);
                    sb.append(indent).append("WHorizontalList ").append(var).append("Row = theme.horizontalList();\n");
                    sb.append(indent).append("WButton ").append(var).append(" = ").append(var)
                        .append("Row.add(theme.button(\"").append(esc(
                            child.text.isEmpty() ? "Select" : child.text)).append("\")).expandX().widget();\n");
                    sb.append(indent).append(var).append(".action = () -> ").append(method(child))
                        .append("();\n");
                    if (child.itemCountSelected >= 0) {
                        sb.append(indent).append(var).append("Row.add(theme.label(\"(")
                            .append(child.itemCountSelected).append(" selected)\"));\n");
                    }
                    tooltip(sb, indent, var, child);
                    sb.append(indent).append(parentVar).append(".add(").append(var).append("Row)")
                        .append(expand(parent, child)).append(";\n");
                    sb.append(indent).append("// \"").append(esc(label))
                        .append("\": open your list screen from the button's action.\n");
                }
                default -> {}
            }
        }
    }

    /** {@code Items.DIAMOND} for a vanilla item id, or a {@code Registries} lookup. */
    private static String itemExpr(String itemId) {
        String key = itemId.contains(":") ? itemId : "minecraft:" + itemId;
        if (!key.startsWith("minecraft:")) {
            return "Registries.ITEM.get(Identifier.of(\"" + esc(key) + "\"))";
        }
        String path = key.substring("minecraft:".length());
        // Items.<ID> exists for every vanilla item, and the item index knows them
        // all, so this never emits a constant the game does not have. Without the
        // extracted assets we fall back to the registry lookup, which always works.
        return com.hackli.guidesigner.assets.AssetStore.get().isVanillaItemConstant(path)
            ? "Items." + path.toUpperCase(java.util.Locale.ROOT)
            : "Registries.ITEM.get(Identifier.of(\"" + esc(key) + "\"))";
    }

    /** {@code Items.ZOMBIE_SPAWN_EGG} for an entity, or null when it has no egg. */
    private static String spawnEggExpr(String entityId) {
        String egg = com.hackli.guidesigner.assets.AssetStore.get().spawnEggOf(entityId);
        if (egg == null) return null;
        return com.hackli.guidesigner.assets.AssetStore.get().isVanillaItemConstant(egg)
            ? "Items." + egg.toUpperCase(java.util.Locale.ROOT)
            : "Registries.ITEM.get(Identifier.of(\"minecraft:" + esc(egg) + "\"))";
    }

    private static void emitHandlerStubs(StringBuilder sb, UiDocument doc) {
        Map<String, UiNode> byId = new LinkedHashMap<>();
        for (UiNode node : doc.interactiveNodes()) {
            if (!node.id.isEmpty() && !byId.containsKey(node.id)) byId.put(node.id, node);
        }

        if (byId.isEmpty()) return;

        sb.append("\n");

        for (Map.Entry<String, UiNode> entry : byId.entrySet()) {
            UiNode node = entry.getValue();

            sb.append("    private void ").append(method(node));
            switch (node.type) {
                case BUTTON -> sb.append("()");
                case TEXTBOX, DROPDOWN -> sb.append("(String value)");
                case CHECKBOX -> sb.append("(boolean value)");
                case SLIDER -> sb.append("(double value)");
                default -> {}
            }
            sb.append(" {\n        // TODO: handle \"").append(esc(node.id)).append("\"\n    }\n\n");
        }
    }

    // ================= helpers =================

    /** Emits {@code var.tooltip = "..."} when the node has hover text. */
    private static void tooltip(StringBuilder sb, String indent, String var, UiNode node) {
        if (node.tooltip != null && !node.tooltip.isEmpty()) {
            sb.append(indent).append(var).append(".tooltip = \"").append(esc(node.tooltip)).append("\";\n");
        }
    }

    /**
     * The {@code .expandX()} suffix for a cell.     *
     * <p>Inside a {@code WTable} this follows the cell setting, so a column keeps
     * its natural width unless the author asked it to grow - that is what makes a
     * table's columns line up. Everywhere else the historical behaviour is kept:
     * most widgets fill the width of their list.</p>
     */
    private static String expand(UiNode parent, UiNode child) {
        if (parent.style == com.hackli.guidesigner.model.ContainerStyle.TABLE) {
            UiNode.Cell cell = child.cell;
            return cell != null && cell.expandX ? ".expandX()" : "";
        }
        return ".expandX()";
    }

    private static String rootTitle(UiNode root) {
        return root.text.isEmpty() ? "Root" : root.text;
    }

    private static String var(String id) {
        String v = DocumentStore.toJava(id);
        return Character.toLowerCase(v.charAt(0)) + v.substring(1);
    }

    /** Generates a Meteor CharFilter lambda for the node's input restrictions, or null. */
    private static String textBoxFilterExpr(UiNode node) {
        boolean needFilter = node.inputFilter != com.hackli.guidesigner.model.InputFilter.NONE || node.maxLength > 0;
        if (!needFilter) return null;

        StringBuilder sb = new StringBuilder();
        sb.append("(text, c) -> ");

        boolean any = false;
        if (node.inputFilter == com.hackli.guidesigner.model.InputFilter.INT) {
            sb.append("(Character.isDigit(c) || c == '-')");
            any = true;
        } else if (node.inputFilter == com.hackli.guidesigner.model.InputFilter.DECIMAL) {
            sb.append("(Character.isDigit(c) || c == '-' || c == '.')");
            any = true;
        }

        if (node.maxLength > 0) {
            if (any) sb.append(" && ");
            sb.append("text.length() < ").append(node.maxLength);
            any = true;
        }

        return any ? sb.toString() : null;
    }

    /** "#rrggbb" / "#rrggbbaa" -> new Color(r, g, b[, a]). */
    private static String colorExpr(String hex) {
        String h = hex != null && hex.startsWith("#") ? hex.substring(1) : (hex == null ? "" : hex);
        if (h.length() == 6) h = h + "ff";
        if (h.length() < 8) h = (h + "00000000").substring(0, 8);
        try {
            int r = Integer.parseInt(h.substring(0, 2), 16);
            int g = Integer.parseInt(h.substring(2, 4), 16);
            int b = Integer.parseInt(h.substring(4, 6), 16);
            int a = Integer.parseInt(h.substring(6, 8), 16);
            return "new Color(" + r + ", " + g + ", " + b + ", " + a + ")";
        } catch (NumberFormatException e) {
            return "Color.WHITE";
        }
    }

    private static String method(UiNode node) {
        String name = node.handler == null || node.handler.isEmpty() ? node.id : node.handler;
        return "on" + DocumentStore.toJava(name);
    }

    private static void header(StringBuilder sb) {
        sb.append("/*\n");
        sb.append(" * Generated by Hackli GUI Studio (GPLv3).\n");
        sb.append(" *\n");
        sb.append(" * This file is part of your Meteor Client plugin. Plugin code developed with\n");
        sb.append(" * Hackli GUI Studio must be released under the GNU General Public License v3:\n");
        sb.append(" *     https://www.gnu.org/licenses/gpl-3.0.txt\n");
        sb.append(" *\n");
        sb.append(" * Static export: no dependency on the Hackli GUI Studio mod at runtime.\n");
        sb.append(" */\n\n");
    }

    private static String q(String value) {
        return "\"" + esc(value) + "\"";
    }

    private static String qList(List<String> values) {
        if (values.isEmpty()) return "new String[]{ \"-\" }";

        List<String> quoted = new ArrayList<>();
        for (String value : values) quoted.add(q(value));

        return "new String[]{ " + String.join(", ", quoted) + " }";
    }

    private static String esc(String value) {
        if (value == null) return "";
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String num(double value) {
        if (value == Math.floor(value) && !Double.isInfinite(value)) {
            return String.valueOf((long) value);
        }
        return String.valueOf(value);
    }
}
